### ISSUE TITLE
Update workflows to cancel any previously in progress ci on consecutive commits

### ISSUE THREAD

**Issue by eddieyu1998** [glimpse-protocol/workflows#2]
# Description

We want to cancel previously running ci jobs to save on resources when we are doing some quick consecutive commits

# Acceptance criteria

All workflows are updated

# Ref

https://twitter.com/sebastienlorber/status/1495776331287646209

https://github.com/nodejs/node/pull/42017

**Comment by eddieyu1998** [comment]
Reopening as it needs more investigation. Apparently it doesn't work straight away by copying and pasting into existing workflows

**Comment by iblancasa** [comment]
Hi! [Reading this article](https://yonatankra.com/7-github-actions-tricks-i-wish-i-knew-before-i-started/#6_Saving_Computation_Time_by_Stopping_Obsolete_Workflows), probably it is not working in your repository because you are using `github.head_ref` (the article suggests `github.ref`).

**Comment by eddieyu1998** [comment]
I change the `github.head_ref` to `github.ref` and now it works wonderfully. Thanks a lot for the help @iblancasa ! Didn't know the difference between `ref` and `head_ref`. Highly appreciate it.

**Comment by eddieyu1998** [comment]
Fixed in the updated commit https://github.com/glimpse-protocol/workflows/commit/f0babec658656e813a078bf8e8e91bb2a09620ea
