### ISSUE TITLE
Incorrect service name used in test script

### ISSUE THREAD

**Issue by tim-hm** [glimpse-protocol/workflows#5]
`./gradlew test ...` is failing when service names have a '-'. For example `vault-market`'s scripting tries to run `./gradlew test --tests "glimpse.vault-market*"` when it should be `glimpse.vault.market.*`

<img width="694" alt="image" src="https://user-images.githubusercontent.com/1335525/161423522-b6e02ef7-4e64-40d5-adc0-688a4f066702.png">

**Comment by samueldobbie** [comment]
The issue comes from the repo names and package names being different for certain repos. Have separated `SERVICE_NAME` into `REPO_NAME` and `PACKAGE_NAME` across the services.
